baseURL = "https://whatmakeart.com/"
languageCode = "en-us"
timeZone = "America/New_York"
title = "What Make Art"
theme = "test"
enableGitInfo = "true"               # allows to get information such as dates from git
timeout = 600000
pagination.pagerSize = 18
googleAnalytics = "G-S4CF1KSMYD"
enableRobotsTXT = true
pluralizelisttitles = false
buildFuture = true # publish pages with a frontmatter date: in the future

[params.author]
email = 'whatmakeart@gmail.com'
name = "Jimmy Kuehnle"

[sitemap]
changefreq = "daily"
priority = 0.5
filename = "sitemap.xml"

[params]
description = "Whatmakeart how to make art tutorials"
twitter = "https://twitter.com/whatmakeart"
instagram = "https://www.instagram.com/whatmakeart/"
youtube = "https://www.youtube.com/channel/UCmGXH-jy0o2CuhqtpxbaQgA"
github = "https://github.com/whatmakeart/"
mastodon = "https://mstdn.social/@whatmakeart"
GithubEdit = "https://github.com/whatmakeart/whatmakeart.github.io/edit/main/content/"

[params.toc]
startLevel = 1     # default is 2
endLevel = 6       # default is 3
minNumHeadings = 1 # default is 2

[contentTypes.'text/markdown']
 
# Tell Hugo to render a lightweight, plain-text LinkIndex for the home page before HTML. 
# That pre-pass only touches .Content for each page, 
# which triggers the render hooks (and thus populates the backlinks).
[outputFormats.LinkIndex]
mediaType = "text/plain"
baseName  = "linkindex"
isPlainText = true
notAlternative = true

[outputs]
home = ["LinkIndex", "HTML", "RSS"]


[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
      style = "monokai"
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false # show line numbers in code blocks
      lineNumbersInTable = false # prevent line numbers from being copied with code
      tabWidth = 4
      noClasses = false

[menu]
[[menu.main]]
name = 'Courses'
url = '/courses'
weight = 10
[[menu.main]]
name = 'Tutorials'
url = '/tags/tutorial/'
weight = 20
[[menu.main]]
name = 'Tags'
url = '/tags'
weight = 30
[[menu.main]]
name = 'Art FAQ'
url = '/art-faq'
weight = 40
[[menu.main]]
name = 'Posts'
url = '/posts'
weight = 50
[[menu.main]]
name = 'About'
url = '/about'
weight = 60


# Keep the normal content mount (default in Hugo)
[module]
  [[module.mounts]]
    source = "content"
    target = "content"   # normal content

  [[module.mounts]]
    source = "content"
    target = "assets"    # <-- note: assets (no /content)
    excludeFiles = ["**/*.md", "**/_index.md", "**/index.md"]
